server:
  port: 10010
spring:
  application:
    name: zuul
zuul:
  routes:
    service-provider: /user/**
    service-consumer: /consumer/**
  prefix: /api
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
