server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eesy_mybatis
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  application:
    name: service-provider
mybatis:
  type-aliases-package: com.fjx.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
