server:
  port: 8888
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka


service-provider: # 服务提供方的Id
  ribbon:   #ribbon默认使用轮询策略，下面改为了随机
    NFLoadBa   lancerRuleClassName: com.netflix.loadbalancer.RandomRule

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms

feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能